### ISSUE TITLE
 Reading a 500M json file using oboe.js will fail even when using oboe.drop

### ISSUE THREAD

**Issue by cnyzgkn** [jimhigson/oboe.js#131] opened 2017-01-03 15:20 UTC
My code is like:
function testOboe() {
    oboe('result.json')
    .node('!.*', function(myObject){
    document.writeln(myObject["globalId"]);
        return oboe.drop;
    }).done(function(finalJson){
    document.writeln("load complete!");
    })
}

**Comment by JuanCaicedo** [comment] 2017-02-04 17:43
Thanks for reporting! I'm going to close since it's a duplicate of https://github.com/jimhigson/oboe.js/issues/68

**Closed by JuanCaicedo** 2017-02-04 17:43 UTC
